version: "3.4"
services:

  integresql:
    image: ghcr.io/allaboutapps/integresql:v1.1.0
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      INTEGRESQL_LOGGER_LEVEL: "info"
      PGHOST: "postgres"
      PGUSER: "postgres"
      PGPORT: "15432"
      PGPASSWORD: ""

  postgres:
    image: postgres:16.2-alpine # should be the same version as used live
    # Apply some performance improvements to pg as these guarantees are not needed while running locally
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=30000' -c 'client_min_messages=warning' -p 15432"
    expose:
      - "15432"
    ports:
      - "15432:15432"
    environment:
      POSTGRES_DB: "development"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: "trust"
#    volumes:
#      - pgvolume:/var/lib/postgresql/data
#
#volumes:
#  pgvolume: # declare a named volume to persist DB data
