name: CI

on: [push, pull_request]

jobs:
  build:
    name: test-on-${{matrix.java}}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          INTEGRESQL_LOGGER_LEVEL: "info"
          POSTGRES_DB: "development"
          POSTGRES_USER: "dbuser"
          POSTGRES_PASSWORD: "dbpass"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      integresql:
        image: ghcr.io/allaboutapps/integresql:v1.1.0
        env:
          PGHOST: "postgres"
          PGUSER: "dbuser"
          PGPASSWORD: "dbpass"
        ports:
          - 5001:5000

    strategy:
      matrix:
        java: [ 17, 21 ]
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        env:
          CI: true
        run: |
          ./gradlew check build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports-jdk-${{matrix.java}}
          path: "**/build/reports"
